apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-rqns
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-rqns
    app.kubernetes.io/part-of: my-app
  name: node-express-hello-rqns
  namespace: mbasti-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-express-hello-rqns
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-express-hello-rqns
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:fee1f4cdccfe4c9a4662399a370b613b4331d78a1bd12f38ff277456d8854240
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
