apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-express-hello-rqns
  namespace: mbasti-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:f200f8fd4ff40b7df5ba302133a558970b0af44823dc9f7b6b28ba49a30214b9
        name: my-nodejs
        resources: {}
status: {}
